[[language]]
name = "latex"
language-servers = ["texlab"]

[language-server.texlab.config.texlab.chktex]
onOpenAndSave = true
onEdit = true

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args =   [ "--synctex-forward", "%l:1:%f", "%p" ]

[language-server.texlab.config.texlab.build]
forwardSearchAfter = true
onSave = true
executable = "tectonic"
args = [ "-X", "compile", "--synctex", "--keep-logs", "--keep-intermediates", "%f" ]

# [language-server.omnisharp.config.FormattingOptions]
# IndentSwitchCaseSectionWhenBlock = false
